# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/chaste/src;/home/chaste/projects/PriyaN")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Config;CxxTest;Python;cell_based_headers;cell_based_libraries;continuum_mechanics_headers;continuum_mechanics_libraries;crypt_headers;crypt_libraries;global_headers;global_libraries;heart_headers;heart_libraries;io_headers;io_libraries;linalg_headers;linalg_libraries;lung_headers;lung_libraries;mesh_headers;mesh_libraries;ode_headers;ode_libraries;pde_headers;pde_libraries")
set(CPACK_COMPONENT_Config_DESCRIPTION "configuration files")
set(CPACK_COMPONENT_Config_DISPLAY_NAME "Config files")
set(CPACK_COMPONENT_Config_GROUP "config")
set(CPACK_COMPONENT_CxxTest_DESCRIPTION "Bundled CxxTest library (http://cxxtest.com/)")
set(CPACK_COMPONENT_CxxTest_DISPLAY_NAME "CxxTest")
set(CPACK_COMPONENT_CxxTest_GROUP "cxxtest")
set(CPACK_COMPONENT_Python_DESCRIPTION "Support python files for Chaste project")
set(CPACK_COMPONENT_Python_DISPLAY_NAME "Python")
set(CPACK_COMPONENT_Python_GROUP "python")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COMPONENT_cell_based_headers_DEPENDS "Chaste_DEPENDS_cell_based_headers")
set(CPACK_COMPONENT_cell_based_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component cell_based")
set(CPACK_COMPONENT_cell_based_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_cell_based_headers_GROUP "headers")
set(CPACK_COMPONENT_cell_based_libraries_DEPENDS "Chaste_DEPENDS_cell_based_libraries")
set(CPACK_COMPONENT_cell_based_libraries_DESCRIPTION "Static Libraries for Chaste component cell_based")
set(CPACK_COMPONENT_cell_based_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_cell_based_libraries_GROUP "libraries")
set(CPACK_COMPONENT_continuum_mechanics_headers_DEPENDS "Chaste_DEPENDS_continuum_mechanics_headers")
set(CPACK_COMPONENT_continuum_mechanics_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component continuum_mechanics")
set(CPACK_COMPONENT_continuum_mechanics_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_continuum_mechanics_headers_GROUP "headers")
set(CPACK_COMPONENT_continuum_mechanics_libraries_DEPENDS "Chaste_DEPENDS_continuum_mechanics_libraries")
set(CPACK_COMPONENT_continuum_mechanics_libraries_DESCRIPTION "Static Libraries for Chaste component continuum_mechanics")
set(CPACK_COMPONENT_continuum_mechanics_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_continuum_mechanics_libraries_GROUP "libraries")
set(CPACK_COMPONENT_crypt_headers_DEPENDS "Chaste_DEPENDS_crypt_headers")
set(CPACK_COMPONENT_crypt_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component crypt")
set(CPACK_COMPONENT_crypt_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_crypt_headers_GROUP "headers")
set(CPACK_COMPONENT_crypt_libraries_DEPENDS "Chaste_DEPENDS_crypt_libraries")
set(CPACK_COMPONENT_crypt_libraries_DESCRIPTION "Static Libraries for Chaste component crypt")
set(CPACK_COMPONENT_crypt_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_crypt_libraries_GROUP "libraries")
set(CPACK_COMPONENT_global_headers_DEPENDS "Chaste_DEPENDS_global_headers")
set(CPACK_COMPONENT_global_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component global")
set(CPACK_COMPONENT_global_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_global_headers_GROUP "headers")
set(CPACK_COMPONENT_global_libraries_DEPENDS "Chaste_DEPENDS_global_libraries")
set(CPACK_COMPONENT_global_libraries_DESCRIPTION "Static Libraries for Chaste component global")
set(CPACK_COMPONENT_global_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_global_libraries_GROUP "libraries")
set(CPACK_COMPONENT_heart_headers_DEPENDS "Chaste_DEPENDS_heart_headers")
set(CPACK_COMPONENT_heart_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component heart")
set(CPACK_COMPONENT_heart_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_heart_headers_GROUP "headers")
set(CPACK_COMPONENT_heart_libraries_DEPENDS "Chaste_DEPENDS_heart_libraries")
set(CPACK_COMPONENT_heart_libraries_DESCRIPTION "Static Libraries for Chaste component heart")
set(CPACK_COMPONENT_heart_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_heart_libraries_GROUP "libraries")
set(CPACK_COMPONENT_io_headers_DEPENDS "Chaste_DEPENDS_io_headers")
set(CPACK_COMPONENT_io_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component io")
set(CPACK_COMPONENT_io_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_io_headers_GROUP "headers")
set(CPACK_COMPONENT_io_libraries_DEPENDS "Chaste_DEPENDS_io_libraries")
set(CPACK_COMPONENT_io_libraries_DESCRIPTION "Static Libraries for Chaste component io")
set(CPACK_COMPONENT_io_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_io_libraries_GROUP "libraries")
set(CPACK_COMPONENT_linalg_headers_DEPENDS "Chaste_DEPENDS_linalg_headers")
set(CPACK_COMPONENT_linalg_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component linalg")
set(CPACK_COMPONENT_linalg_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_linalg_headers_GROUP "headers")
set(CPACK_COMPONENT_linalg_libraries_DEPENDS "Chaste_DEPENDS_linalg_libraries")
set(CPACK_COMPONENT_linalg_libraries_DESCRIPTION "Static Libraries for Chaste component linalg")
set(CPACK_COMPONENT_linalg_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_linalg_libraries_GROUP "libraries")
set(CPACK_COMPONENT_lung_headers_DEPENDS "Chaste_DEPENDS_lung_headers")
set(CPACK_COMPONENT_lung_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component lung")
set(CPACK_COMPONENT_lung_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_lung_headers_GROUP "headers")
set(CPACK_COMPONENT_lung_libraries_DEPENDS "Chaste_DEPENDS_lung_libraries")
set(CPACK_COMPONENT_lung_libraries_DESCRIPTION "Static Libraries for Chaste component lung")
set(CPACK_COMPONENT_lung_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_lung_libraries_GROUP "libraries")
set(CPACK_COMPONENT_mesh_headers_DEPENDS "Chaste_DEPENDS_mesh_headers")
set(CPACK_COMPONENT_mesh_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component mesh")
set(CPACK_COMPONENT_mesh_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_mesh_headers_GROUP "headers")
set(CPACK_COMPONENT_mesh_libraries_DEPENDS "Chaste_DEPENDS_mesh_libraries")
set(CPACK_COMPONENT_mesh_libraries_DESCRIPTION "Static Libraries for Chaste component mesh")
set(CPACK_COMPONENT_mesh_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_mesh_libraries_GROUP "libraries")
set(CPACK_COMPONENT_ode_headers_DEPENDS "Chaste_DEPENDS_ode_headers")
set(CPACK_COMPONENT_ode_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component ode")
set(CPACK_COMPONENT_ode_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_ode_headers_GROUP "headers")
set(CPACK_COMPONENT_ode_libraries_DEPENDS "Chaste_DEPENDS_ode_libraries")
set(CPACK_COMPONENT_ode_libraries_DESCRIPTION "Static Libraries for Chaste component ode")
set(CPACK_COMPONENT_ode_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_ode_libraries_GROUP "libraries")
set(CPACK_COMPONENT_pde_headers_DEPENDS "Chaste_DEPENDS_pde_headers")
set(CPACK_COMPONENT_pde_headers_DESCRIPTION "C++ header files (.hpp) for Chaste component pde")
set(CPACK_COMPONENT_pde_headers_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_pde_headers_GROUP "headers")
set(CPACK_COMPONENT_pde_libraries_DEPENDS "Chaste_DEPENDS_pde_libraries")
set(CPACK_COMPONENT_pde_libraries_DESCRIPTION "Static Libraries for Chaste component pde")
set(CPACK_COMPONENT_pde_libraries_DISPLAY_NAME "Static Libraries")
set(CPACK_COMPONENT_pde_libraries_GROUP "libraries")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "cmake, g++, libopenmpi-dev, petsc-dev (>= 2.3.3-14), libhdf5-openmpi-dev, xsdcxx, libboost-serialization-dev, libboost-filesystem-dev, libparmetis-dev, libxerces-c3-dev, libsundials-serial-dev, libvtk5-dev, python-lxml, python-rdflib")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "valgrind, libfltk1.1")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "libgoogle-perftools-dev, doxygen, graphviz, eclipse-cdt, gnuplot")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/chaste/projects/PriyaN;Chaste;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/chaste/src/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "Chaste 2019.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Chaste 2019.1")
set(CPACK_OUTPUT_CONFIG_FILE "/home/chaste/projects/PriyaN/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Chaste Team <chaste-admin@maillist.ox.ac.uk>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "
 Chaste is a general purpose simulation package aimed at multi-scale,
 computationally demanding problems arising in biology and physiology.
 Current functionality includes tissue and cell level electrophysiology,
 discrete tissue modelling, and soft tissue modelling. The package is
 being developed by a team mainly based in the Computational Biology Group
 at Oxford University Computing Laboratory, and development draws on expertise
 from software engineering, high performance computing, mathematical modelling
 and scientific computing.
 .
 The main website for Chaste can be found at
 http://www.cs.ox.ac.uk/chaste
")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Chaste (Cancer, Heart and Soft Tissue Environment).")
set(CPACK_PACKAGE_FILE_NAME "Chaste-2019.1-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Chaste 2019.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Chaste 2019.1")
set(CPACK_PACKAGE_NAME "Chaste")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Computational Biology Group - Computer Science - University of Oxford")
set(CPACK_PACKAGE_VERSION "2019.1")
set(CPACK_PACKAGE_VERSION_MAJOR "2019")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.13/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/chaste/projects/PriyaN/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/chaste/projects/PriyaN/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
