function heterotypicboundaryall = importfile_heterotypicboundaryall(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HETEROTYPICBOUNDARY = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  HETEROTYPICBOUNDARY = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  heterotypicboundary = importfile("/Users/Priya/testoutput/TestMammaryMonolayerWT/results_from_time_0/heterotypicboundary.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jun-2021 08:58:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "fractional_length", "total_length", "fractional_neighbours", "total_neighbours"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
heterotypicboundaryall = readtable(filename, opts);

end